### ISSUE TITLE
Raw spirogram values from COPDGene

### ISSUE THREAD

**Issue by sgadgil6** [Google-Health/genomics-research#14]
Thank you for releasing the code to your paper "Inference of chronic obstructive pulmonary disease with deep learning on raw spirograms identifies new genetic loci and improves risk models". 

In the paper, you used COPDGene as one of your evaluation datasets. How were you able to get the raw spirometry curves (flow-volume) from COPDGene? I looked at the dataset and I couldn’t find any raw spirogram data – I could only find the summary statistics (FEV1, FVC, etc.)
 
It would really be helpful if you could tell me how you got the raw values from the COPDGene dataset.

**Comment by justincosentino** [comment]
Hi @sgadgil6, 

In our paper, we evaluated only our PRS models using the genetic data and COPD labels available in COPDGene. Unfortunately we have not gone through the COPDGene spirometry data access process. Please reach out to COPDGene for more information.
