### ISSUE TITLE
Model configuration is nonetype

### ISSUE THREAD

**Issue by KasperFischer** [Google-Health/genomics-research#2]
Hi,

I am running DeepNull with my own phenocovar file with the following command:

```
python -m deepnull.main \
  --input_tsv="/home/usr/folder/DeepNull/my_phenocovar.tsv" \
  --output_tsv="/home/usr/folder/DeepNull/my_phenocovar_output.tsv" \
  --target="Pheno" \
  --covariates="Sex,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10"

```
The columns of the file `my_phenocovar.tsv`  are the folowing and I don't have GPU.

```
FID	IID	Pheno	Sex	PC1	PC2	PC3	PC4	PC5	PC6	PC7	PC8	PC9	PC10
```
Running the model with the defeault settings gives me this error

```
I0118 10:17:24.925369 139753410072768 main.py:72] Loading data from /home/usr/folder/DeepNull/my_phenocovar.tsv
Traceback (most recent call last):
  File "/data/usr/conda/envs/deepnull/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/usr/conda/envs/deepnull/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/usr/conda/envs/deepnull/lib/python3.8/site-packages/deepnull/main.py", line 114, in <module>
    app.run(main)
  File "/data/usr/conda/envs/deepnull/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/data/usr/conda/envs/deepnull/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/data/usr/conda/envs/deepnull/lib/python3.8/site-packages/deepnull/main.py", line 76, in main
    if _MODEL_CONFIG.value is None:
AttributeError: 'NoneType' object has no attribute 'value'
```

It seems as if DeepNull cannot detect a model configuration file, so I have tried to specify it explicitly as such, but this gives the exact same error message:

```
python -m deepnull.main \
  --model_config="/data/usr/conda/envs/deepnull/lib/python3.8/site-packages/deepnull/config.py:deepnull" \
  --input_tsv="/home/usr/folder/DeepNull/my_phenocovar.tsv" \
  --output_tsv="/home/usr/folder/DeepNull/my_phenocovar_output.tsv" \
  --target="Pheno" \
  --covariates="Sex,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10"
```

Does anyone know what is going on here, and why the model configuration keep getting defines as a nontype?

**Comment by cmclean** [comment]
Hi @KasperFischer,

Your particular error is occurring at https://github.com/Google-Health/genomics-research/blob/main/nonlinear-covariate-gwas/main.py#L76 and indicates that the `_MODEL_CONFIG` variable itself is `None` rather than an object holding configuration flags. This suggests that the `ml_collections` library (used to define this flag) may not be installed properly.

To help root cause the issue, how exactly did you install DeepNull on your machine? And what happens when you try to execute all of its tests?

```
  python -m deepnull.config_test
  python -m deepnull.data_test
  python -m deepnull.metrics_test
  python -m deepnull.model_test
  python -m deepnull.train_eval_test
```

**Comment by KasperFischer** [comment]
I installed deepnull with `pip3`as my baseline pip refers to python 2.7. So I typed `pip3 install --upgrade deepnull`, to install with python3.

All the above tests result in an `OK` at the comand line.

**Comment by cmclean** [comment]
Hi @KasperFischer,

@fhormoz was able to reproduce the issue. After digging, we noticed that `ml_collections` version `0.1.0` does not return a value from its `DEFINE_config_file` function, whereas version `0.1.1` does.

We will push an update to GitHub shortly. In the meantime, there are two independent workarounds that you could use:

Option 1: Upgrade to `ml_collections` version `0.1.1`. This is not available via PyPI yet though.

Option 2: Make the following two changes to `main.py`:

Add as a new line 65:  `FLAGS = flags.FLAGS`

Modify lines 76-80:
```
  if FLAGS.model_config is None:
    full_config = config.get_config('deepnull')
  else:
    full_config = FLAGS.model_config
```

**Comment by cmclean** [comment]
Hi @KasperFischer,

Thanks for raising this! We've released version v.0.2.1 of DeepNull to fix the problem. Please let us know if you run into any other issues.
